package uk.ac.soton.comp2211.calculator;

public enum RunwayProperty {

    STOPWAY_LOWER_VALUE, STOPWAY_HIGHER_VALUE,
    CLEARWAY_LOWER_VALUE, CLEARWAY_HIGHER_VALUE,

    ASDA_VALUE, TORA_VALUE, TODA_VALUE, LDA_VALUE,

    STOPWAY_LOWER_LOCATION, STOPWAY_HIGHER_LOCATION,
    CLEARWAY_LOWER_LOCATION, CLEARWAY_HIGHER_LOCATION,
    THRESHOLD_LOWER_LOCATION, THRESHOLD_HIGHER_LOCATION,

}
