package uk.ac.soton.comp2211.calculator;

public enum RunwayValue {

    TODA, TORA, ASDA, LDA, TOTAL, STRIP, CLEARWAY, STOPWAY,
    LOWER_THRESHOLD, HIGHER_THRESHOLD, OBSTACLE_OFFSET,
    RESA, BLAST_PROTECTION

}
